<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'WPDevAutoThumb\\Contracts\\LoggerInterface' => 'get8cb7197a6061f665cf42e22186a1105f',
);

    protected function get8cb7197a6061f665cf42e22186a1105f()
    {
        $object = new WPDevAutoThumb\Helpers\Logger();
        return $object;
    }

}
